### ISSUE TITLE
Separate the menu "engine" from the menu[s] definition

### ISSUE THREAD

**Issue by avih** [carmanaught/mpvcontextmenu#1]
This is nice :)

I always had a plan to make something like this (including proper cascading menus - though with the same issue as yours - impossible to click and leave it on screen), but didn't get to it.

One suggestion though, would be to separate the menu engine (the lua-tcl interaction) from the actual menu definitions (i.e. labels and commands). In my proof of concept script the menu is small enough to fit, but in your case the menu definition is quite extensive, and so it'll be much cleaner IMO if it's separate from the engine.

Such separation might also allow to build other "engines", e.g. possibly written in lua like the OSC without requiring tcl/tk, or maybe gtk menus etc. The point is that the menu definition could be an independent thing, with possibly more than one backend which could render it.

Keep up the good work! (no, I haven't tried it yet.. but the screenshot is nice ;) )

**Comment by carmanaught** [comment]
Thanks!

I was really glad when I started to figure out how what you'd written worked, since I really missed having a right-click menu in my video player, which I was particularly used to having one with Bomi, which is why I replicated much of the layout of the menu here.

That could be an interesting idea actually, since I did consider something like lua-lgi (Lua GObject Introspection) to make a Gtk based menu when I was having some troubles with Tcl, though I'm less familiar with proper Gtk and have only really learnt Lua from starting to use mpv.

In some ways, the actual building of the menu argument list does separate it in part from the Tcl side by simply being a list of arguments that the Tcl script must parse, so theoretically as long as you write the building "engine" (if I understand you correctly) as something that will parse the menu output, that keeps the two partially separated. Then it's just a thing of specifying which subprocess to run.

But if using a predetermined layout, I could see having the menu definitions as a separate file, using whatever functions someone prefers to build the menu, then passing that to the build script which itself could have multiple menu building interactions with different "engines".

**Comment by carmanaught** [comment]
~~Well, I've been doing some testing and based on the way the menu is defined, and that the menu definition differs between no file loaded and after a file is loaded, it seems somewhat difficult to move the menu definition into another file, separate from the menu building.~~

It turns out I was doing it slightly backwards, and the function call to build the menu needs to come from the menu definitions to allow for the unloaded/loaded state to work correctly. Reworking the code, the menu engine can be in a separate file which can have the logic for handling different builders written into it.

As an aside, I did manage to add back the click and leave on screen functionality, though that's likely an engine specific thing, depending on whether other menu engines would support that functionality.

**Comment by carmanaught** [comment]
The second commit above is me realizing I had the terminology for the engine/builder backwards.

This separates the engine from the menu definitions (where the engine is called from) and the engine itself handles the builder (the Tcl script). This allows for either the engine itself to handle multiple builders (with the associated checks/logic in it, or someone could write an entire other engine and use the definitions that way.

I prefer the approach of using the mp.utils.subprocess to do it for stuff like the Tk menu, though having something like the OSC (using mp.assdraw perhaps?) may make sense to write a separate engine rather than using it as a subprocess.

**Comment by carmanaught** [comment]
With the changes already made to separate the definitions from the menu engine and the addition of a second menu builder, making use the menu engine, I feel this issue is addressed.

Anyone that wants to should be able to write another engine entirely and call that from the definitions file (to ensure the menu status) and have it work.

With the changes to the menu engine as well, someone simply wishing to generate a different style of menu can write a menu builder that receives the items sent via the mp.utils.subprocess and interacts with the engine by passing JSON values back, or even changing how the engine builds the items for a specific menu builder.
